collections:
  # Install a collection from Ansible Galaxy.
  - name: geerlingguy.php_roles
    version: 0.9.3
    source: https://galaxy.ansible.com
    
  #- name: lucab85.ansible_role_motd
  #  source: https://galaxy.ansible.com
